---
networks:
  default:
    name: ${STACK_NAME}-hello
    attachable: true
    external: false
  shared:
    name: ${STACK_NAME}-shared
    attachable: true
    external: false

services:

  nginx:
    command: ["nginx", "-g", "daemon off;"]
    image: nginx
    container_labels:
      org.company.country: england
    configs:
      /etc/nginx/nginx.conf:
        sourceFile: 'nginx.conf'
      /etc/nginx/conf.d/default.conf:
        content: |
          server {
            location ${NGINX_LOCATION} {
              root ${NGINX_FOLDER};
            }
            location /status {
              default_type application/json;
              return 200 '{"status":"success"}';
            }
          }
    env_file: .env
    environment:
      NGINX_FOLDER: /usr/share/nginx/html/
    networks:
      - default
    replicas: 2
    # TODO: Implement replicated and global, support changing between em.
    stop_signal: SIGQUIT
    stop_grace_period: 10
    placement:
      preferences: [{ spread: node.hostname }]
      max_replicas_per_node: 2
      constraints:
        - node.labels.purpose == generic
    endpoint_spec:
      ports:
        - protocol: tcp
          published: 8080
          target: 80
    # TODO: Implement healthcheck
#    health_check:
#      test: "string"
#      interval: 5s
#      timeout: 5s
#      retries: 3
#      start_period: 5s
#      start_interval: 1s
    # TODO: Implement mounts
    mounts:
      /etc/nginx/:
        source: "web-data"
        type: "volume"
        # type: "bind"
        readonly: true
