---
networks:
  default:
    name: ${STACK_NAME}-hello
    attachable: true
    external: false

services:

  nginx:
    image: nginx
    # TODO: Rename to container_labels
    # TODO: Implement service_labels
    labels:
      org.company.country: england
    configs:
      /etc/nginx/nginx.conf:
        # TODO: Rename to source: instead of file:
        file: 'examples/nginx.conf'
      /etc/nginx/conf.d/default.conf:
        content: |
          server {
            location / {
              root ${NGINX_FOLDER};
            }
          }
    # TODO: Implement env_file
    environment:
      NGINX_FOLDER: html
    networks:
      - default
    replicas: 2
    stop_signal: SIGQUIT
    placement:
      max_replicas_per_node: 2
      constraints:
        - node.labels.purpose == generic
    endpoint_spec:
      ports:
        - protocol: tcp
          published: 8080
          target: 80
    mounts:
      /etc/nginx/:
        source: "web-data"
        type: "volume" # bind
        readonly: true
