---
networks:
  default:
    name: ${STACK_NAME}-hello
    attachable: true
    external: false
  shared:
    name: external
    external: true

services:

  # {% if echo_servers is defined %}
  # {% for entry in echo_servers %}
  echo-server-{{ entry }}:
    image: mendhak/http-https-echo:37
  # {% endfor %}
  # {% endif %}

  nginx:
    command: ["nginx", "-g", "daemon off;"]
    image: nginx
    container_labels:
      org.company.country: england
    configs:
      /etc/nginx/nginx.conf:
        sourceFile: 'nginx.conf'
      /etc/nginx/conf.d/default.conf:
        content: |
          server {
            location ${NGINX_LOCATION} {
              root ${NGINX_FOLDER};
            }
            location /status {
              default_type application/json;
              return 200 '{"status":"success"}';
            }
          }
    env_file: .env
    environment:
      NGINX_FOLDER: /usr/share/nginx/html/
    networks:
      - default
      - shared
    replicas: 2
    stop_signal: SIGQUIT
    stop_grace_period: 10
    placement:
      preferences: [{ spread: node.hostname }]
      max_replicas_per_node: 2
      constraints:
        - node.labels.purpose == generic
    endpoint_spec:
      ports:
        - protocol: tcp
          published: 8080
          target: 80
    health_check:
      test: ["CMD", "true"]
      interval: 5000000 # 5s
      timeout: 5000000 # 5s
      retries: 3
      start_period: 5000000 # 5s
      start_interval: 1000000 # 1s
    mounts:
      /etc/nginx/:
        source: "web-data"
        type: "volume" # "bind|volume"
        readonly: true
