---
name: Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install --no-audit --no-fund --cache .npm
      - run: npx tsc
      - run: node src/index.js --help

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install --no-audit --no-fund --cache .npm
      - run: npx eslint .

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install --no-audit --no-fund --cache .npm
      - run: npx tsc
      - run: npm test

  generate-schema-has-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install --no-audit --no-fund --cache .npm
      - run: npx tsc
      - run: node src/index.js generate-schema > schema.json
      - run: git diff --exit-code -- schema.json || (>&2 echo "schema.json is not up to date. Please run node src/index.js generate-schema > schema.json"; exit 1)
